export interface peopleTypr {
	EmployeeNumber: number;
	Surname: string;
	GivenName: string;
	Gender: string;
	City: string;
	JobTitle: string;
	DepartmentName: string;
	StoreLocation: string;
	Division: string;
	Age: number;
	LengthService: number;
	AbsentHours: number;
	BusinessUnit: string;
}

export const PeopleData: peopleTypr[] = [
	{
		EmployeeNumber: 1,
		Surname: 'Gutierrez',
		GivenName: 'Molly',
		Gender: 'F',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 32,
		LengthService: 6.018478474,
		AbsentHours: 36.57730606,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 2,
		Surname: 'Hardwick',
		GivenName: 'Stephen',
		Gender: 'M',
		City: 'Courtenay',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 40,
		LengthService: 5.532444578,
		AbsentHours: 30.16507231,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 3,
		Surname: 'Delgado',
		GivenName: 'Chester',
		Gender: 'M',
		City: 'Richmond',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Richmond',
		Division: 'Stores',
		Age: 48,
		LengthService: 4.389973118,
		AbsentHours: 83.80779766,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 4,
		Surname: 'Simon',
		GivenName: 'Irene',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 44,
		LengthService: 3.081735738,
		AbsentHours: 70.02016505,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 5,
		Surname: 'Delvalle',
		GivenName: 'Edward',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 35,
		LengthService: 3.619091448,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 6,
		Surname: 'Jones',
		GivenName: 'Ernie',
		Gender: 'M',
		City: 'Richmond',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Richmond',
		Division: 'Stores',
		Age: 48,
		LengthService: 2.717692452,
		AbsentHours: 81.83007916,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 7,
		Surname: 'Buford',
		GivenName: 'Ralph',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 50,
		LengthService: 10.157918,
		AbsentHours: 60.49507152,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 8,
		Surname: 'Lee',
		GivenName: 'Gregory',
		Gender: 'M',
		City: 'Sechelt',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'West Vancouver',
		Division: 'Stores',
		Age: 36,
		LengthService: 4.432122862,
		AbsentHours: 30.07290192,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 9,
		Surname: 'Smith',
		GivenName: 'Jerry',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 58,
		LengthService: 6.940120524,
		AbsentHours: 181.630819,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 10,
		Surname: 'Beard',
		GivenName: 'Robert',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 39,
		LengthService: 13.848321,
		AbsentHours: 30.66440832,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 11,
		Surname: 'Mathis',
		GivenName: 'John',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 46,
		LengthService: 4.872038321,
		AbsentHours: 28.01835332,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 12,
		Surname: 'Barajas',
		GivenName: 'John',
		Gender: 'M',
		City: 'Kamloops',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 40,
		LengthService: 3.793042148,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 13,
		Surname: 'Leonard',
		GivenName: 'James',
		Gender: 'M',
		City: 'North Vancouver',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'North Vancouver',
		Division: 'Stores',
		Age: 37,
		LengthService: 3.621141838,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 14,
		Surname: 'Davis',
		GivenName: 'Janet',
		Gender: 'F',
		City: 'Vananda',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 30,
		LengthService: 4.583328091,
		AbsentHours: 34.33444296,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 15,
		Surname: 'Bell',
		GivenName: 'Thomas',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 49,
		LengthService: 4.883225,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 16,
		Surname: 'Combs',
		GivenName: 'Danny',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 42,
		LengthService: 19.107198,
		AbsentHours: 21.65982312,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 17,
		Surname: 'Vivanco',
		GivenName: 'Anne',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 48,
		LengthService: 9.940272,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 18,
		Surname: 'Craig',
		GivenName: 'Bobbie',
		Gender: 'F',
		City: 'West Vancouver',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'West Vancouver',
		Division: 'Stores',
		Age: 41,
		LengthService: 2.559053659,
		AbsentHours: 55.09983109,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 19,
		Surname: 'Jones',
		GivenName: 'Ilona',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 51,
		LengthService: 5.30277286,
		AbsentHours: 81.59554037,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 20,
		Surname: 'Watkins',
		GivenName: 'Jan',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 36,
		LengthService: 11.22628,
		AbsentHours: 94.66856131,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 21,
		Surname: 'Callaway',
		GivenName: 'Jesus',
		Gender: 'M',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 57,
		LengthService: 3.300303735,
		AbsentHours: 108.3801763,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 22,
		Surname: 'Hammett',
		GivenName: 'Josephine',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 24,
		LengthService: 3.147510228,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 23,
		Surname: 'Jarman',
		GivenName: 'Sandra',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 49,
		LengthService: 6.5335,
		AbsentHours: 67.74078948,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 24,
		Surname: 'Butler',
		GivenName: 'Jennifer',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 60,
		LengthService: 4.465036581,
		AbsentHours: 158.7045089,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 25,
		Surname: 'Simons',
		GivenName: 'Larry',
		Gender: 'M',
		City: 'Nanaimo',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 35,
		LengthService: 4.626920266,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 26,
		Surname: 'Mason',
		GivenName: 'Penny',
		Gender: 'F',
		City: 'Aldergrove',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Aldergrove',
		Division: 'Stores',
		Age: 35,
		LengthService: 3.101925634,
		AbsentHours: 48.0170507,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 27,
		Surname: 'Burton',
		GivenName: 'Theodore',
		Gender: 'M',
		City: 'Kelowna',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 41,
		LengthService: 4.557230329,
		AbsentHours: 42.78802656,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 28,
		Surname: 'Hunt',
		GivenName: 'Joseph',
		Gender: 'M',
		City: 'Trail',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Trail',
		Division: 'Stores',
		Age: 35,
		LengthService: 5.174673648,
		AbsentHours: 34.52427221,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 29,
		Surname: 'Loiselle',
		GivenName: 'Thomas',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 40,
		LengthService: 12.185467,
		AbsentHours: 59.88316464,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 30,
		Surname: 'Nguyen',
		GivenName: 'William',
		Gender: 'M',
		City: 'Aldergrove',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Aldergrove',
		Division: 'Stores',
		Age: 49,
		LengthService: 4.313617694,
		AbsentHours: 100.6740987,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 31,
		Surname: 'Schrupp',
		GivenName: 'James',
		Gender: 'M',
		City: 'Penticton',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 38,
		LengthService: 3.493533521,
		AbsentHours: 9.522523814,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 32,
		Surname: 'Donaldson',
		GivenName: 'Adriana',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 42,
		LengthService: 19.006436,
		AbsentHours: 38.88332344,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 33,
		Surname: 'Thompson',
		GivenName: 'Felipe',
		Gender: 'M',
		City: 'Duncan',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Quesnel',
		Division: 'Stores',
		Age: 49,
		LengthService: 5.775266268,
		AbsentHours: 129.8357633,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 34,
		Surname: 'Livingston',
		GivenName: 'Lester',
		Gender: 'M',
		City: 'Kelowna',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 77,
		LengthService: 3.203849714,
		AbsentHours: 44.2731088,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 35,
		Surname: 'Ashley',
		GivenName: 'Emma',
		Gender: 'F',
		City: 'Crawford Bay',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Cranbrook',
		Division: 'Stores',
		Age: 23,
		LengthService: 2.992041355,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 36,
		Surname: 'Davis',
		GivenName: 'Jeffery',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 36,
		LengthService: 18.196064,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 37,
		Surname: 'Farris',
		GivenName: 'Augustina',
		Gender: 'F',
		City: 'Courtenay',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 51,
		LengthService: 4.641869886,
		AbsentHours: 75.25704812,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 38,
		Surname: 'Colman',
		GivenName: 'Katherine',
		Gender: 'F',
		City: 'Port Hardy',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 40,
		LengthService: 6.192268184,
		AbsentHours: 58.97153025,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 39,
		Surname: 'Martin',
		GivenName: 'Daniel',
		Gender: 'M',
		City: 'Kelowna',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 52,
		LengthService: 4.29126449,
		AbsentHours: 134.6683839,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 40,
		Surname: 'Atencio',
		GivenName: 'Morris',
		Gender: 'M',
		City: 'Logan Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 20,
		LengthService: 4.483391669,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 41,
		Surname: 'Harrod',
		GivenName: 'Gloria',
		Gender: 'F',
		City: 'Abbotsford',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Abbotsford',
		Division: 'Stores',
		Age: 44,
		LengthService: 4.862142071,
		AbsentHours: 78.34173929,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 42,
		Surname: 'Bell',
		GivenName: 'Angelo',
		Gender: 'M',
		City: 'Dawson Creek',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Dawson Creek',
		Division: 'Stores',
		Age: 67,
		LengthService: 2.183958352,
		AbsentHours: 168.9957664,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 43,
		Surname: 'Kelley',
		GivenName: 'Virginia',
		Gender: 'F',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 41,
		LengthService: 2.018782807,
		AbsentHours: 56.21994065,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 44,
		Surname: 'Turner',
		GivenName: 'Stephen',
		Gender: 'M',
		City: 'Surrey',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Surrey',
		Division: 'Stores',
		Age: 62,
		LengthService: 5.473604647,
		AbsentHours: 152.6467667,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 45,
		Surname: 'Mortimer',
		GivenName: 'Cecilia',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 28,
		LengthService: 5.776657666,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 46,
		Surname: 'Stutts',
		GivenName: 'Belle',
		Gender: 'F',
		City: 'Surrey',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Surrey',
		Division: 'Stores',
		Age: 49,
		LengthService: 5.357402979,
		AbsentHours: 80.24254043,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 47,
		Surname: 'Bryant',
		GivenName: 'John',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 50,
		LengthService: 1,
		AbsentHours: 78.7532824,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 48,
		Surname: 'Nolan',
		GivenName: 'John',
		Gender: 'M',
		City: 'Squamish',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Squamish',
		Division: 'Stores',
		Age: 33,
		LengthService: 5.654808747,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 49,
		Surname: 'Allison',
		GivenName: 'Connie',
		Gender: 'F',
		City: 'Good Hope Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Terrace',
		Division: 'Stores',
		Age: 51,
		LengthService: 3.9855896,
		AbsentHours: 88.91127783,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 50,
		Surname: 'McAllister',
		GivenName: 'Greg',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounting Clerk',
		DepartmentName: 'Accounting',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 38,
		LengthService: 20.678832,
		AbsentHours: 21.38553248,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 51,
		Surname: 'Murry',
		GivenName: 'Adam',
		Gender: 'M',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 30,
		LengthService: 7.560140987,
		AbsentHours: 3.737100223,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 52,
		Surname: 'Price',
		GivenName: 'David',
		Gender: 'M',
		City: 'Penticton',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 43,
		LengthService: 0.385746182,
		AbsentHours: 38.06658377,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 53,
		Surname: 'McCoy',
		GivenName: 'Corey',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 50,
		LengthService: 5.702536846,
		AbsentHours: 116.2269635,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 54,
		Surname: 'Baker',
		GivenName: 'Linda',
		Gender: 'F',
		City: 'Nanaimo',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 34,
		LengthService: 4.721105791,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 55,
		Surname: 'Shultz',
		GivenName: 'Charles',
		Gender: 'M',
		City: 'Abbotsford',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Abbotsford',
		Division: 'Stores',
		Age: 29,
		LengthService: 3.28103742,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 56,
		Surname: 'Medina',
		GivenName: 'Bonita',
		Gender: 'F',
		City: 'Sidney',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 50,
		LengthService: 3.653801673,
		AbsentHours: 77.13030678,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 57,
		Surname: 'Houston',
		GivenName: 'Harold',
		Gender: 'M',
		City: 'Coquitlam',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 24,
		LengthService: 4.796216863,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 58,
		Surname: 'Mejia',
		GivenName: 'James',
		Gender: 'M',
		City: 'Chilliwack',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Chilliwack',
		Division: 'Stores',
		Age: 42,
		LengthService: 4.124606978,
		AbsentHours: 24.79287091,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 59,
		Surname: 'Bates',
		GivenName: 'Charles',
		Gender: 'M',
		City: 'Okanagan Mission',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 54,
		LengthService: 4.060790515,
		AbsentHours: 121.4480075,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 60,
		Surname: 'Ross',
		GivenName: 'Robert',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 43,
		LengthService: 4.197598793,
		AbsentHours: 59.7836809,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 61,
		Surname: 'Heller',
		GivenName: 'Joseph',
		Gender: 'M',
		City: 'Ganges',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 42,
		LengthService: 5.101161761,
		AbsentHours: 55.62426288,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 62,
		Surname: 'Murray',
		GivenName: 'Faye',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 55,
		LengthService: 10.623616,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 63,
		Surname: 'Allen',
		GivenName: 'Michelle',
		Gender: 'F',
		City: 'Prince George',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 31,
		LengthService: 0.775517909,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 64,
		Surname: 'Jones',
		GivenName: 'Harvey',
		Gender: 'M',
		City: 'Atlin',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Terrace',
		Division: 'Stores',
		Age: 43,
		LengthService: 5.843569409,
		AbsentHours: 55.05895104,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 65,
		Surname: 'Nystrom',
		GivenName: 'Jane',
		Gender: 'F',
		City: 'Kamloops',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 35,
		LengthService: 3.679095448,
		AbsentHours: 44.6346054,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 66,
		Surname: 'Albright',
		GivenName: 'Paul',
		Gender: 'M',
		City: 'Whistler',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Squamish',
		Division: 'Stores',
		Age: 39,
		LengthService: 5.748053523,
		AbsentHours: 42.45739254,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 67,
		Surname: 'Lovely',
		GivenName: 'Janet',
		Gender: 'F',
		City: 'Surrey',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Surrey',
		Division: 'Stores',
		Age: 22,
		LengthService: 5.897640636,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 68,
		Surname: 'Strayhorn',
		GivenName: 'Billie',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 39,
		LengthService: 11.885504,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 69,
		Surname: 'Jones',
		GivenName: 'Tammy',
		Gender: 'F',
		City: 'Spences Bridge',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 46,
		LengthService: 2.024655355,
		AbsentHours: 107.7955005,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 70,
		Surname: 'Gay',
		GivenName: 'Donald',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 44,
		LengthService: 12.305714,
		AbsentHours: 78.84098352,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 71,
		Surname: 'Green',
		GivenName: 'Earnest',
		Gender: 'M',
		City: 'New Westminister',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminister',
		Division: 'Stores',
		Age: 52,
		LengthService: 4.589520028,
		AbsentHours: 110.1543068,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 72,
		Surname: 'Riley',
		GivenName: 'Wendy',
		Gender: 'F',
		City: 'Gibsons',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'West Vancouver',
		Division: 'Stores',
		Age: 35,
		LengthService: 3.947661015,
		AbsentHours: 33.93440994,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 73,
		Surname: 'Malizia',
		GivenName: 'Randall',
		Gender: 'M',
		City: 'Vernon',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Vernon',
		Division: 'Stores',
		Age: 42,
		LengthService: 3.387128544,
		AbsentHours: 28.60483097,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 74,
		Surname: 'Lopez',
		GivenName: 'Florence',
		Gender: 'F',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 40,
		LengthService: 3.285283682,
		AbsentHours: 44.9874293,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 75,
		Surname: 'Howell',
		GivenName: 'Carol',
		Gender: 'F',
		City: 'Fauquier',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Trail',
		Division: 'Stores',
		Age: 46,
		LengthService: 1.991692074,
		AbsentHours: 126.5011301,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 76,
		Surname: 'Chico',
		GivenName: 'Joyce',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 45,
		LengthService: 5.567973876,
		AbsentHours: 19.6191458,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 77,
		Surname: 'White',
		GivenName: 'Anthony',
		Gender: 'M',
		City: 'Kamloops',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 38,
		LengthService: 6.095617444,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 78,
		Surname: 'Smith',
		GivenName: 'Danny',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 35,
		LengthService: 8.348239,
		AbsentHours: 44.97411152,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 79,
		Surname: 'Porter',
		GivenName: 'Ana',
		Gender: 'F',
		City: 'Mackenzie',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 41,
		LengthService: 4.711743887,
		AbsentHours: 45.95478779,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 80,
		Surname: 'Depaz',
		GivenName: 'Shari',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 43,
		LengthService: 1.778630937,
		AbsentHours: 83.3173005,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 81,
		Surname: 'Witkowski',
		GivenName: 'Alice',
		Gender: 'F',
		City: 'Squamish',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Squamish',
		Division: 'Stores',
		Age: 54,
		LengthService: 2.870591513,
		AbsentHours: 136.3424045,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 82,
		Surname: 'Alvarez',
		GivenName: 'Kenneth',
		Gender: 'M',
		City: 'Nanaimo',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 46,
		LengthService: 4.416249838,
		AbsentHours: 53.3120259,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 83,
		Surname: 'Morales',
		GivenName: 'Soledad',
		Gender: 'F',
		City: 'Gold Bridge',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 47,
		LengthService: 4.252453434,
		AbsentHours: 96.6132406,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 84,
		Surname: 'Burden',
		GivenName: 'Alexis',
		Gender: 'F',
		City: 'Penticton',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 51,
		LengthService: 2.964089468,
		AbsentHours: 140.9111414,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 85,
		Surname: 'Dyal',
		GivenName: 'William',
		Gender: 'M',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 33,
		LengthService: 2.301876593,
		AbsentHours: 31.69229831,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 86,
		Surname: 'Hayden',
		GivenName: 'Kenneth',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 47,
		LengthService: 4.149329545,
		AbsentHours: 12.68410865,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 87,
		Surname: 'Caban',
		GivenName: 'Joshua',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 34,
		LengthService: 13.828331,
		AbsentHours: 54.30033232,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 88,
		Surname: 'Knight',
		GivenName: 'Mildred',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 37,
		LengthService: 18.641316,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 89,
		Surname: 'Thurmond',
		GivenName: 'Linda',
		Gender: 'F',
		City: 'Duncan',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Quesnel',
		Division: 'Stores',
		Age: 45,
		LengthService: 6.837239767,
		AbsentHours: 103.3493697,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 90,
		Surname: 'Monroe',
		GivenName: 'Terra',
		Gender: 'F',
		City: 'Kelowna',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 26,
		LengthService: 3.983950436,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 91,
		Surname: 'Velez',
		GivenName: 'Colleen',
		Gender: 'F',
		City: 'Good Hope Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Terrace',
		Division: 'Stores',
		Age: 37,
		LengthService: 3.569517999,
		AbsentHours: 49.84641191,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 92,
		Surname: 'Martin',
		GivenName: 'Lisa',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 40,
		LengthService: 1.223785,
		AbsentHours: 58.28770605,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 93,
		Surname: 'Godfrey',
		GivenName: 'Ramon',
		Gender: 'M',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 48,
		LengthService: 5.534431308,
		AbsentHours: 110.8124796,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 94,
		Surname: 'Jackson',
		GivenName: 'Monica',
		Gender: 'F',
		City: 'Fort Fraser',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 52,
		LengthService: 5.333357014,
		AbsentHours: 158.6843997,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 95,
		Surname: 'Craig',
		GivenName: 'Cristina',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 37,
		LengthService: 4.677505826,
		AbsentHours: 73.47603875,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 96,
		Surname: 'Schooley',
		GivenName: 'Daniel',
		Gender: 'M',
		City: 'Nelson',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nelson',
		Division: 'Stores',
		Age: 29,
		LengthService: 4.853084899,
		AbsentHours: 2.187241945,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 97,
		Surname: 'Wireman',
		GivenName: 'Jacquie',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 51,
		LengthService: 4.954787053,
		AbsentHours: 99.80856689,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 98,
		Surname: 'Tripp',
		GivenName: 'Simone',
		Gender: 'F',
		City: 'Kamloops',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 39,
		LengthService: 1.914256944,
		AbsentHours: 34.77626973,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 99,
		Surname: 'Cousins',
		GivenName: 'Jessica',
		Gender: 'F',
		City: 'Kaslo',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Cranbrook',
		Division: 'Stores',
		Age: 26,
		LengthService: 4.850275414,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 100,
		Surname: 'Drake',
		GivenName: 'Mildred',
		Gender: 'F',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 46,
		LengthService: 7.40795942,
		AbsentHours: 81.7411048,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 101,
		Surname: 'Gilreath',
		GivenName: 'Mary',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 39,
		LengthService: 5.28876626,
		AbsentHours: 51.75805976,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 102,
		Surname: 'Lundin',
		GivenName: 'Edwina',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 49,
		LengthService: 2.992767917,
		AbsentHours: 121.0074252,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 103,
		Surname: 'Gleason',
		GivenName: 'Esther',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 43,
		LengthService: 16.587192,
		AbsentHours: 48.37309828,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 104,
		Surname: 'Sharma',
		GivenName: 'Donald',
		Gender: 'M',
		City: 'Nanaimo',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 55,
		LengthService: 2.020945438,
		AbsentHours: 137.4598877,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 105,
		Surname: 'Hash',
		GivenName: 'Yvonne',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 44,
		LengthService: 4.03442867,
		AbsentHours: 98.5576777,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 106,
		Surname: 'Harris',
		GivenName: 'Arnold',
		Gender: 'M',
		City: 'Creston',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Cranbrook',
		Division: 'Stores',
		Age: 29,
		LengthService: 2.920694436,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 107,
		Surname: 'Massey',
		GivenName: 'Christie',
		Gender: 'F',
		City: 'Wynndel',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Cranbrook',
		Division: 'Stores',
		Age: 46,
		LengthService: 4.834791047,
		AbsentHours: 44.00185941,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 108,
		Surname: 'Webber',
		GivenName: 'Hobert',
		Gender: 'M',
		City: 'Muncho Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Fort St John',
		Division: 'Stores',
		Age: 27,
		LengthService: 4.51966396,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 109,
		Surname: 'Edmondson',
		GivenName: 'Cynthia',
		Gender: 'F',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 37,
		LengthService: 4.934654158,
		AbsentHours: 39.10172396,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 110,
		Surname: 'Paschall',
		GivenName: 'Marjorie',
		Gender: 'F',
		City: 'Muncho Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Fort St John',
		Division: 'Stores',
		Age: 50,
		LengthService: 5.505354659,
		AbsentHours: 138.9330403,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 111,
		Surname: 'Johnson',
		GivenName: 'Dexter',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 46,
		LengthService: 4.74303968,
		AbsentHours: 63.03007856,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 112,
		Surname: 'Fox',
		GivenName: 'Keith',
		Gender: 'M',
		City: 'Creston',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Cranbrook',
		Division: 'Stores',
		Age: 50,
		LengthService: 5.319611026,
		AbsentHours: 98.3228922,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 113,
		Surname: 'Kamen',
		GivenName: 'Alan',
		Gender: 'M',
		City: 'Kitimat',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Terrace',
		Division: 'Stores',
		Age: 39,
		LengthService: 1.733551364,
		AbsentHours: 56.30433228,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 114,
		Surname: 'Ogden',
		GivenName: 'Nancy',
		Gender: 'F',
		City: 'Lac La Hache',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Williams Lake',
		Division: 'Stores',
		Age: 37,
		LengthService: 5.272417507,
		AbsentHours: 25.46792975,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 115,
		Surname: 'Ervin',
		GivenName: 'Patricia',
		Gender: 'F',
		City: 'Armstrong',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Vernon',
		Division: 'Stores',
		Age: 47,
		LengthService: 3.813679718,
		AbsentHours: 96.88371667,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 116,
		Surname: 'Clark',
		GivenName: 'Pauline',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 50,
		LengthService: 3.450234407,
		AbsentHours: 118.490501,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 117,
		Surname: 'Andrews',
		GivenName: 'Debra',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 40,
		LengthService: 6.277340487,
		AbsentHours: 34.02042059,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 118,
		Surname: 'Calderon',
		GivenName: 'Sybil',
		Gender: 'F',
		City: 'Aldergrove',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Aldergrove',
		Division: 'Stores',
		Age: 36,
		LengthService: 6.283404129,
		AbsentHours: 72.79408579,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 119,
		Surname: 'Torres',
		GivenName: 'Lee',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 33,
		LengthService: 3.616228,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 120,
		Surname: 'Ward',
		GivenName: 'James',
		Gender: 'M',
		City: 'Abbotsford',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Abbotsford',
		Division: 'Stores',
		Age: 32,
		LengthService: 7.100916929,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 121,
		Surname: 'Browning',
		GivenName: 'Christiane',
		Gender: 'F',
		City: 'Duncan',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Quesnel',
		Division: 'Stores',
		Age: 58,
		LengthService: 6.547789836,
		AbsentHours: 153.2632323,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 122,
		Surname: 'Wurth',
		GivenName: 'William',
		Gender: 'M',
		City: 'Duncan',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Quesnel',
		Division: 'Stores',
		Age: 23,
		LengthService: 5.192754104,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 123,
		Surname: 'Prescott',
		GivenName: 'Wesley',
		Gender: 'M',
		City: 'Quesnel',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Quesnel',
		Division: 'Stores',
		Age: 43,
		LengthService: 7.921398042,
		AbsentHours: 53.84737103,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 124,
		Surname: 'Dunham',
		GivenName: 'Ligia',
		Gender: 'F',
		City: 'Hixon',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 52,
		LengthService: 4.990343166,
		AbsentHours: 113.9617749,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 125,
		Surname: 'Garrett',
		GivenName: 'Steve',
		Gender: 'M',
		City: 'Fauquier',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Trail',
		Division: 'Stores',
		Age: 45,
		LengthService: 3.39067547,
		AbsentHours: 79.10668824,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 126,
		Surname: 'Alexander',
		GivenName: 'Tyrone',
		Gender: 'M',
		City: 'Surrey',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Surrey',
		Division: 'Stores',
		Age: 35,
		LengthService: 5.764585657,
		AbsentHours: 29.98231177,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 127,
		Surname: 'Cheek',
		GivenName: 'Mary',
		Gender: 'F',
		City: 'Wynndel',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Cranbrook',
		Division: 'Stores',
		Age: 37,
		LengthService: 1.976125041,
		AbsentHours: 68.40403177,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 128,
		Surname: 'Ackerman',
		GivenName: 'Carrie',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 43,
		LengthService: 21.122314,
		AbsentHours: 30.99399888,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 129,
		Surname: 'Johnson',
		GivenName: 'Patricia',
		Gender: 'F',
		City: 'Ocean Falls',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Ocean Falls',
		Division: 'Stores',
		Age: 24,
		LengthService: 3.769958819,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 130,
		Surname: 'Haley',
		GivenName: 'Carey',
		Gender: 'M',
		City: 'West Vancouver',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'West Vancouver',
		Division: 'Stores',
		Age: 45,
		LengthService: 6.680159831,
		AbsentHours: 40.05948151,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 131,
		Surname: 'Hall',
		GivenName: 'Maria',
		Gender: 'F',
		City: 'Vallican',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Trail',
		Division: 'Stores',
		Age: 32,
		LengthService: 3.122804778,
		AbsentHours: 49.65651125,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 132,
		Surname: 'Bunch',
		GivenName: 'Terra',
		Gender: 'F',
		City: 'North Pender Island',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 39,
		LengthService: 3.731981529,
		AbsentHours: 94.2773662,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 133,
		Surname: 'Martin',
		GivenName: 'Terry',
		Gender: 'M',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 35,
		LengthService: 1.881003024,
		AbsentHours: 58.09452779,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 134,
		Surname: 'Bass',
		GivenName: 'Brian',
		Gender: 'M',
		City: 'Montney',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Fort St John',
		Division: 'Stores',
		Age: 49,
		LengthService: 4.205191727,
		AbsentHours: 62.16083824,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 135,
		Surname: 'Wagner',
		GivenName: 'Robert',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Payable Clerk',
		DepartmentName: 'Accounts Payable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 54,
		LengthService: 17.149135,
		AbsentHours: 30.45802032,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 136,
		Surname: 'McBride',
		GivenName: 'Joanne',
		Gender: 'F',
		City: 'Ganges',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 44,
		LengthService: 3.729336444,
		AbsentHours: 90.81179196,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 137,
		Surname: 'Johnson',
		GivenName: 'Paul',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 36,
		LengthService: 18.480086,
		AbsentHours: 37.1157124,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 138,
		Surname: 'Cook',
		GivenName: 'Anthony',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 55,
		LengthService: 11.44132,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 139,
		Surname: 'Loch',
		GivenName: 'Dean',
		Gender: 'M',
		City: 'North Vancouver',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'North Vancouver',
		Division: 'Stores',
		Age: 43,
		LengthService: 5.174066619,
		AbsentHours: 63.18923992,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 140,
		Surname: 'Defoor',
		GivenName: 'James',
		Gender: 'M',
		City: 'Prince George',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 56,
		LengthService: 4.927399666,
		AbsentHours: 101.9347516,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 141,
		Surname: 'Wadlington',
		GivenName: 'Arthur',
		Gender: 'M',
		City: 'Burns Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 43,
		LengthService: 2.480452998,
		AbsentHours: 45.48992662,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 142,
		Surname: 'Harte',
		GivenName: 'Vanessa',
		Gender: 'F',
		City: 'Midway',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Trail',
		Division: 'Stores',
		Age: 50,
		LengthService: 3.006138301,
		AbsentHours: 124.2025327,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 143,
		Surname: 'Galindo',
		GivenName: 'Zachary',
		Gender: 'M',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 49,
		LengthService: 4.687620059,
		AbsentHours: 56.92397595,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 144,
		Surname: 'Reardon',
		GivenName: 'Kenneth',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 39,
		LengthService: 16.8497,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 145,
		Surname: 'Flores',
		GivenName: 'Doris',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 44,
		LengthService: 11.954267,
		AbsentHours: 111.7755846,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 146,
		Surname: 'Busch',
		GivenName: 'Alice',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 35,
		LengthService: 13.707758,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 147,
		Surname: 'Phillips',
		GivenName: 'Alfredo',
		Gender: 'M',
		City: 'Westwold',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Vernon',
		Division: 'Stores',
		Age: 61,
		LengthService: 3.439750719,
		AbsentHours: 96.260697,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 148,
		Surname: 'Lopez',
		GivenName: 'Christopher',
		Gender: 'M',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 47,
		LengthService: 3.44226196,
		AbsentHours: 58.15296878,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 149,
		Surname: 'Fernandez',
		GivenName: 'Emma',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 34,
		LengthService: 5.689747,
		AbsentHours: 40.14572515,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 150,
		Surname: 'Westling',
		GivenName: 'Sharonda',
		Gender: 'F',
		City: 'Vananda',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 37,
		LengthService: 7.02162411,
		AbsentHours: 92.24730012,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 151,
		Surname: 'Pelletier',
		GivenName: 'Ronald',
		Gender: 'M',
		City: 'Terrace',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Terrace',
		Division: 'Stores',
		Age: 57,
		LengthService: 5.586855486,
		AbsentHours: 116.0821581,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 152,
		Surname: 'Chacon',
		GivenName: 'William',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 37,
		LengthService: 2.759389,
		AbsentHours: 24.50390384,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 153,
		Surname: 'Petty',
		GivenName: 'Leland',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 37,
		LengthService: 2.519988839,
		AbsentHours: 17.06972082,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 154,
		Surname: 'Whitmire',
		GivenName: 'Ernestine',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 40,
		LengthService: 6.408469,
		AbsentHours: 90.16966119,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 155,
		Surname: 'Rivers',
		GivenName: 'Matthew',
		Gender: 'M',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 49,
		LengthService: 6.154288207,
		AbsentHours: 46.52578004,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 156,
		Surname: 'Meyers',
		GivenName: 'Kim',
		Gender: 'F',
		City: 'Golden',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Cranbrook',
		Division: 'Stores',
		Age: 55,
		LengthService: 4.507594802,
		AbsentHours: 156.6886593,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 157,
		Surname: 'Hebert',
		GivenName: 'Sheree',
		Gender: 'F',
		City: 'Port Coquitlam',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Port Coquitlam',
		Division: 'Stores',
		Age: 27,
		LengthService: 5.882383018,
		AbsentHours: 14.38568387,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 158,
		Surname: 'Jacques',
		GivenName: 'Pearl',
		Gender: 'F',
		City: 'Vernon',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Vernon',
		Division: 'Stores',
		Age: 51,
		LengthService: 2.856147379,
		AbsentHours: 113.2580344,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 159,
		Surname: 'Valdez',
		GivenName: 'Gabriela',
		Gender: 'F',
		City: 'Hixon',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 61,
		LengthService: 2.771944271,
		AbsentHours: 159.968214,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 160,
		Surname: 'Vidrine',
		GivenName: 'Harold',
		Gender: 'M',
		City: 'Sechelt',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'West Vancouver',
		Division: 'Stores',
		Age: 66,
		LengthService: 4.235105015,
		AbsentHours: 223.778841,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 161,
		Surname: 'Carbone',
		GivenName: 'Edith',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 43,
		LengthService: 23.746003,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 162,
		Surname: 'Hernandez',
		GivenName: 'Leonard',
		Gender: 'M',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 40,
		LengthService: 3.839194051,
		AbsentHours: 79.12363725,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 163,
		Surname: 'Campbell',
		GivenName: 'Frank',
		Gender: 'M',
		City: 'White Rock',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'White Rock',
		Division: 'Stores',
		Age: 57,
		LengthService: 6.032330926,
		AbsentHours: 154.2577252,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 164,
		Surname: 'Raley',
		GivenName: 'Charlie',
		Gender: 'M',
		City: 'Aldergrove',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Aldergrove',
		Division: 'Stores',
		Age: 31,
		LengthService: 4.08229079,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 165,
		Surname: 'Rayfield',
		GivenName: 'Robert',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 35,
		LengthService: 17.80744,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 166,
		Surname: 'Shea',
		GivenName: 'Melinda',
		Gender: 'F',
		City: 'Richmond',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Richmond',
		Division: 'Stores',
		Age: 52,
		LengthService: 6.524270599,
		AbsentHours: 88.45913805,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 167,
		Surname: 'Coleman',
		GivenName: 'David',
		Gender: 'M',
		City: 'Muncho Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Fort St John',
		Division: 'Stores',
		Age: 30,
		LengthService: 4.994952013,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 168,
		Surname: 'Haynes',
		GivenName: 'Patrick',
		Gender: 'M',
		City: 'Whistler',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Squamish',
		Division: 'Stores',
		Age: 54,
		LengthService: 5.582832837,
		AbsentHours: 95.49894843,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 169,
		Surname: 'Bonilla',
		GivenName: 'Frederick',
		Gender: 'M',
		City: 'Surrey',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Surrey',
		Division: 'Stores',
		Age: 49,
		LengthService: 3.415872649,
		AbsentHours: 120.0797189,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 170,
		Surname: 'Tobin',
		GivenName: 'Sonia',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Accounts Receiveable Clerk',
		DepartmentName: 'Accounts Receiveable',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 43,
		LengthService: 13.56324,
		AbsentHours: 0,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 171,
		Surname: 'Wood',
		GivenName: 'Denise',
		Gender: 'F',
		City: 'Logan Lake',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 30,
		LengthService: 5.287380572,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 172,
		Surname: 'Guajardo',
		GivenName: 'Cynthia',
		Gender: 'F',
		City: 'Summerland',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 42,
		LengthService: 0.696873054,
		AbsentHours: 82.89702302,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 173,
		Surname: 'Marshall',
		GivenName: 'Caroline',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 49,
		LengthService: 5.039542872,
		AbsentHours: 121.3682638,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 174,
		Surname: 'Ray',
		GivenName: 'James',
		Gender: 'M',
		City: 'Prince George',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Prince George',
		Division: 'Stores',
		Age: 38,
		LengthService: 3.999675679,
		AbsentHours: 34.20118293,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 175,
		Surname: 'Baum',
		GivenName: 'Stephanie',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Auditor',
		DepartmentName: 'Audit',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 45,
		LengthService: 14.410268,
		AbsentHours: 69.47820963,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 176,
		Surname: 'Dubin',
		GivenName: 'Joesph',
		Gender: 'M',
		City: 'Kelowna',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 44,
		LengthService: 4.48261494,
		AbsentHours: 56.19587246,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 177,
		Surname: 'Giles',
		GivenName: 'Sarah',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 43,
		LengthService: 4.978325753,
		AbsentHours: 61.49474478,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 178,
		Surname: 'Layman',
		GivenName: 'Angelica',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 42,
		LengthService: 5.982794346,
		AbsentHours: 60.09046813,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 179,
		Surname: 'Martin',
		GivenName: 'Michaela',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 44,
		LengthService: 0.840480646,
		AbsentHours: 66.31549844,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 180,
		Surname: 'Williams',
		GivenName: 'Michael',
		Gender: 'M',
		City: 'North Vancouver',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'North Vancouver',
		Division: 'Stores',
		Age: 45,
		LengthService: 3.842333733,
		AbsentHours: 71.55570239,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 181,
		Surname: 'Hoyt',
		GivenName: 'Arnold',
		Gender: 'M',
		City: 'West Vancouver',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'West Vancouver',
		Division: 'Stores',
		Age: 37,
		LengthService: 6.982080942,
		AbsentHours: 33.94380532,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 182,
		Surname: 'Belliveau',
		GivenName: 'Tina',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 33,
		LengthService: 3.959062909,
		AbsentHours: 46.92397933,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 183,
		Surname: 'Hoffman',
		GivenName: 'Marvin',
		Gender: 'M',
		City: 'Langley',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Langley',
		Division: 'Stores',
		Age: 40,
		LengthService: 3.204713851,
		AbsentHours: 40.23300149,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 184,
		Surname: 'Slavin',
		GivenName: 'Paul',
		Gender: 'M',
		City: 'Port Coquitlam',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Port Coquitlam',
		Division: 'Stores',
		Age: 37,
		LengthService: 4.947165495,
		AbsentHours: 29.16170217,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 185,
		Surname: 'Rosenfeld',
		GivenName: 'Mary',
		Gender: 'F',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 42,
		LengthService: 2.048207893,
		AbsentHours: 44.15691237,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 186,
		Surname: 'Bryan',
		GivenName: 'Larry',
		Gender: 'M',
		City: 'Vancouver',
		JobTitle: 'Auditor',
		DepartmentName: 'Audit',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 45,
		LengthService: 12.688114,
		AbsentHours: 47.51121024,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 187,
		Surname: 'Hines',
		GivenName: 'Oswaldo',
		Gender: 'M',
		City: 'Kamloops',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kamloops',
		Division: 'Stores',
		Age: 34,
		LengthService: 4.044062622,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 188,
		Surname: 'Finley',
		GivenName: 'Anna',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Auditor',
		DepartmentName: 'Audit',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 49,
		LengthService: 1,
		AbsentHours: 121.7851932,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 189,
		Surname: 'McCaffery',
		GivenName: 'Francis',
		Gender: 'M',
		City: 'Victoria',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Victoria',
		Division: 'Stores',
		Age: 35,
		LengthService: 5.028810793,
		AbsentHours: 31.13908709,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 190,
		Surname: 'Ditch',
		GivenName: 'Diana',
		Gender: 'F',
		City: 'New Westminster',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'New Westminster',
		Division: 'Stores',
		Age: 53,
		LengthService: 5.138841132,
		AbsentHours: 79.22102251,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 191,
		Surname: 'Foster',
		GivenName: 'Bonnie',
		Gender: 'F',
		City: 'Vancouver',
		JobTitle: 'Auditor',
		DepartmentName: 'Audit',
		StoreLocation: 'Vancouver',
		Division: 'FinanceAndAccounting',
		Age: 43,
		LengthService: 25.934345,
		AbsentHours: 38.55781831,
		BusinessUnit: 'HeadOffice'
	},
	{
		EmployeeNumber: 192,
		Surname: 'Mitchell',
		GivenName: 'Mary',
		Gender: 'F',
		City: 'Chilliwack',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Chilliwack',
		Division: 'Stores',
		Age: 19,
		LengthService: 4.47318993,
		AbsentHours: 0,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 193,
		Surname: 'Peterson',
		GivenName: 'Brenda',
		Gender: 'F',
		City: 'Huntingdon',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Abbotsford',
		Division: 'Stores',
		Age: 46,
		LengthService: 5.312088904,
		AbsentHours: 44.74428082,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 194,
		Surname: 'Stokley',
		GivenName: 'George',
		Gender: 'M',
		City: 'Nelson',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nelson',
		Division: 'Stores',
		Age: 44,
		LengthService: 4.41770495,
		AbsentHours: 93.42104381,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 195,
		Surname: 'Hauser',
		GivenName: 'Harold',
		Gender: 'M',
		City: 'Burnaby',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Burnaby',
		Division: 'Stores',
		Age: 48,
		LengthService: 5.696230561,
		AbsentHours: 96.65594514,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 196,
		Surname: 'Russell',
		GivenName: 'James',
		Gender: 'M',
		City: 'Nanaimo',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Nanaimo',
		Division: 'Stores',
		Age: 50,
		LengthService: 1.265974742,
		AbsentHours: 71.73266923,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 197,
		Surname: 'Mott',
		GivenName: 'Daniel',
		Gender: 'M',
		City: 'Yale',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Chilliwack',
		Division: 'Stores',
		Age: 59,
		LengthService: 3.241373868,
		AbsentHours: 109.2478897,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 198,
		Surname: 'Fernandez',
		GivenName: 'Michael',
		Gender: 'M',
		City: 'Aiyansh',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Terrace',
		Division: 'Stores',
		Age: 35,
		LengthService: 4.453742125,
		AbsentHours: 12.57657646,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 199,
		Surname: 'Burton',
		GivenName: 'Norman',
		Gender: 'M',
		City: 'Richmond',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Richmond',
		Division: 'Stores',
		Age: 51,
		LengthService: 3.682661001,
		AbsentHours: 34.0739579,
		BusinessUnit: 'Stores'
	},
	{
		EmployeeNumber: 200,
		Surname: 'Forrest',
		GivenName: 'Tamara',
		Gender: 'F',
		City: 'Penticton',
		JobTitle: 'Baker',
		DepartmentName: 'Bakery',
		StoreLocation: 'Kelowna',
		Division: 'Stores',
		Age: 57,
		LengthService: 5.885415633,
		AbsentHours: 154.8111128,
		BusinessUnit: 'Stores'
	}
];
